#+hugo_base_dir: ./
* Posts
:PROPERTIES:
:export_hugo_section: posts
:END:

** DONE First Post! :org:hugo:@scribbles:
CLOSED: [2022-11-12 Sat 18:56]
:PROPERTIES:
:EXPORT_FILE_NAME: first-post
:END:

I used to maintain a rather clunky blog, which was a mixture of =Gulp 4= and =Sass=, but finally gathered my willpower to move on to a lightweight platform.
+ Due to all the heavy assets, the blog template itself (devoid of any content) took up about 10MB. Some parts were brought from a obscure source, so I really did not have a clear understanding of what was going on under the hood.
+ Adding a new page was a pain with the absence of an universial template; dealing with all the HTML tags and what not. I wanted a platform where I could easily jot down stuff, not a polished space without any real content.
That was when I ran into [[https://gohugo.io][Hugo]] paired with [[https://ox-hugo.scripter.co/][ox-Hugo]], a backend that exports Org-mode docs in Emacs to Hugo-compatible MD files. And after my first take, I can't help but appreciate the convenience!
+ The whole [[https://github.com/paul-kang-1/pr-website][Blog repo]] stays under 1KB, and I can leverage tools like =Org-capture= to easily create new posts.
+ With the below command and some use of [[https://ox-hugo.scripter.co/doc/auto-export-on-saving/][autosave setup]], you can introduce hot loading to the local development.
  #+begin_src sh
    hugo server --buildDrafts --navigateToChanged
  #+end_src
Anyway, it feels like I've finally found a nice and cozy setup. Let's see where this leads to!
